//ASTRO
//ASTROPEDA
//OUR WORKS
//WILL REMAIN OUR WORKS
//WELL
//IT WAS BUILT 
//WITH NODE
//JS
//AND IT IS FREE TO USE
//IF YOU ARE CHAGRED 
//THEN LOOK FOR A CHEAP BROKER
//BOTS ARE EXPENISE TO DELOPY, RUN AND MAINTAIN
// SO KEEP IN MIND
//ALSO NOTE THAT
// IF YOU MISUSE OR ABUSE THIS BOT
//YOUR ACCOUNT WILL NOT MAY, I ASSURE YOU 
//IT WILL BE BANNED, SO USE
//RESPONISBLY
//LOVE FROM ASTRO
//ASTA MD 2024 VERSION.....
















































































let smd = require('../lib/plugins')
smd({
    cmdname: "astro",
    desc: "take notice",
    category: "Astro",
    filename: __filename
},async (message, citel) => {
    //null cmd lol
}


)